site_name: "Matrix Semirings in JAX"
site_description: The documentation for using matrix semirings in JAX.
site_author: Anand Balakrishnan
site_url: https://anand-bala.github.io/automatax

repo_url: https://github.com/anand-bala/automatax
repo_name: anand-bala/automatax

theme:
  name: "material"
  custom_dir: overrides

edit_uri: "" # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate
strict: true # Don't allow warnings during the build process


extra_javascript:
  # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - _static/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - _static/custom_style.css


markdown_extensions:
  - pymdownx.arithmatex: # Render LaTeX via MathJax
      generic: true
  - pymdownx.superfences # Seems to enable syntax highlighting when used with the Material theme.
  - pymdownx.details # Allowing hidden expandable regions denoted by ???
  - pymdownx.snippets: # Include one Markdown file into another
      base_path: docs
  - admonition
  - toc:
      permalink: "¤" # Adds a clickable permalink to each section heading
      toc_depth: 4

plugins:
  - search # default search plugin; needs manually re-enabling when using any other plugins
  - autorefs # Cross-links to headings
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            separate_signature: true
            show_signature_annotations: true
            members_order: source # order methods according to their order of definition in the source code, not alphabetical order


nav:
  - Overview: "index.md"
  - semirings.md
  - "api.md"
